services:
  server-service:
    image: ghcr.io/cobblemon/cobblemon-conquest:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: cobblemon-conquest-server-service
    pull_policy: daily
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      MOTD: "Cobblemon Conquest Main Server"
      PACKWIZ_URL: /modpack/pack.toml
      TYPE: FABRIC
      VERSION: 1.21.1
      FABRIC_LAUNCHER_VERSION: 1.1.1
      FABRIC_LOADER_VERSION: 0.18.4

      RCON_PASSWORD: "${RCON_PASSWORD:-minecraft}"

      DIFFICULTY: easy

      SPAWN_ANIMALS: "false"
      SPAWN_MONSTERS: "false"
      SPAWN_PROTECTION: 0
      SPAWN_NPCS: "true"
    
      VIEW_DISTANCE: 6
      SIMULATION_DISTANCE: 6
      MAX_PLAYERS: 10

      ENABLE_COMMAND_BLOCK: "true"

      INIT_MEMORY: 4G
      MAX_MEMORY: 6G

      ENABLE_WHITELIST: "false"

      REPLACE_ENV_IN_PLACE: "true"
      REPLACE_ENV_VARIABLE_PREFIX: "CFG_"
      REPLACE_ENV_DURING_SYNC: "true"

      CFG_POSTGRES_HOST: database
      CFG_POSTGRES_PORT: 5432
      CFG_POSTGRES_DB: cobblemon_conquest
      CFG_POSTGRES_USER: admin
      CFG_POSTGRES_PASSWORD: cobblemonpassword
    
    ports:
      - "24454:24454/udp"
    
    volumes:
      - ./data/server-service:/data
      - ./modpack:/modpack:ro
  
  limbo-service:
    image: ghcr.io/quozul/picolimbo:latest
    container_name: cobblemon-conquest-limbo-service
    restart: unless-stopped

  proxy:
    image: ghcr.io/cobblemon/cobblemon-conquest-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: cobblemon-conquest-proxy
    pull_policy: daily
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      TYPE: VELOCITY
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Cobblemon Conquest Proxy
      REPLACE_ENV_VARIABLES: "true"
      PLUGINS_FILE: /config/plugins.txt

      REPLACE_ENV_IN_PLACE: "true"
      REPLACE_ENV_VARIABLE_PREFIX: "CFG_"
      REPLACE_ENV_DURING_SYNC: "true"

      CFG_POSTGRES_HOST: database
      CFG_POSTGRES_PORT: 5432
      CFG_POSTGRES_DB: cobblemon_conquest
      CFG_POSTGRES_USER: admin
      CFG_POSTGRES_PASSWORD: cobblemonpassword
    ports:
      - "25577:25565"
    volumes:
      - ./proxy:/config
      - ./data/proxy:/server

  database:
    image: postgres:18.2
    container_name: cobblemon-conquest-database
    pull_policy: daily
    restart: unless-stopped
    environment:
      POSTGRES_DB: cobblemon_conquest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cobblemonpassword
    volumes:
      - ./data/database:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin --dbname cobblemon_conquest"]
      interval: 5s
      timeout: 5s
      retries: 10
