name = "cobblemon-conquest"
author = "albercl"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ea09aae01d37dcca5edfcb28b298b09ce0db1d1c6823bcf738f3acc2fb8ab3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
