name = "cobblemon-conquest"
author = "albercl"
version = "1.1.0-RC1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c31dba8317d368bba9ddc1d0142103227ae9f1b79df0834a4f9a9c0d29703e8b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
