name = "cobblemon-conquest"
author = "albercl"
version = "1.1.0-RC1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f790b4bcf8fda05fa974feb35307e29daae671b9a31c425b8a91876c0ffac72"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
