# Don't change this! Version used to track needed updates.
version = 0
testIfSpaceEmpty = false
paintingsHaveCollision = false
showOtherPlayersPaintings = true
automaticImageResizing = false
uploadPermissionLevel = 0
maxUserImageWidth = 2048
maxUserImageHeight = 2048
maxUserImages = 10
minPaintingResolution = 8
maxPaintingResolution = 256
maxPacketsPerSecond = 20
packetSize = 65536
packetSplitInterval = 250